Add Debian package build script
Running `make apt-package` will build a Debian repository under
`hack/apt/_output/apt` which will hold a debian package for Tanzu CLI
v0.26.0 for AMD64 and one for ARM64.

Signed-off-by: Marc Khouzam <kmarc@vmware.com>

diff --git a/cli/core/Makefile b/cli/core/Makefile
--- a/cli/core/Makefile
+++ b/cli/core/Makefile
@@ -159,6 +159,20 @@ release-%: ## Create release for a platform
 	$(MAKE) build-tanzu-core-cli-oci-$(OS)-$(ARCH)
 
 ## --------------------------------------
+## OS Packages
+## --------------------------------------
+.PHONY: apt-package
+apt-package: ## Build a debian package to use with APT
+	@if [ "$$(command -v docker)" == "" ]; then \
+		echo "Docker required to build apt package" ;\
+		exit 1 ;\
+	fi
+
+	@# To call this target, the VERSION variable must be set by the caller.  The version must match an existing release
+	@# of the tanzu CLI on Github. E.g., VERSION=v0.26.0 make apt-package	
+	docker run --rm -e VERSION=$${VERSION} -v $(ROOT_DIR):$(ROOT_DIR) ubuntu $(MODULE_ROOT_DIR)/hack/apt/build_package.sh
+
+## --------------------------------------
 ## Testing
 ## --------------------------------------
 
