Add RPM package build script (#3792)
Signed-off-by: Marc Khouzam <kmarc@vmware.com>

diff --git a/cli/core/Makefile b/cli/core/Makefile
--- a/cli/core/Makefile
+++ b/cli/core/Makefile
@@ -172,6 +172,17 @@ apt-package: ## Build a debian package to use with APT
 	@# of the tanzu CLI on Github. E.g., VERSION=v0.26.0 make apt-package	
 	docker run --rm -e VERSION=$${VERSION} -v $(ROOT_DIR):$(ROOT_DIR) ubuntu $(MODULE_ROOT_DIR)/hack/apt/build_package.sh
 
+.PHONY: rpm-package
+rpm-package: ## Build an RPM package
+	@if [ "$$(command -v docker)" == "" ]; then \
+		echo "Docker required to build rpm package" ;\
+		exit 1 ;\
+	fi
+
+	@# To call this target, the VERSION variable must be set by the caller.  The version must match an existing release
+	@# of the tanzu CLI on Github. E.g., VERSION=v0.26.0 make rpm-package
+	docker run --rm -e VERSION=$${VERSION} -v $(ROOT_DIR):$(ROOT_DIR) fedora $(MODULE_ROOT_DIR)/hack/rpm/build_package.sh
+
 ## --------------------------------------
 ## Testing
 ## --------------------------------------
